"$schema" = "https://conductor.build/schemas/settings.repo.schema.json"

[scripts]
setup = "npm ci"
archive = "true"
run_mode = "concurrent"

[scripts.run.dev]
available_in = [ "local" ]
command = "npm run dev -- --port $CONDUCTOR_PORT"
default = true
icon = "play"

[scripts.run.test]
command = "npm test"
icon = "test-tube"

[scripts.run.format-check]
command = "npm run format:check"
icon = "braces"
