ALTER TABLE wyc_ratings ADD COLUMN entered_by INT NULL AFTER examiner;

ALTER TABLE wyc_ratings ADD COLUMN entered_at TIMESTAMP NULL DEFAULT NULL AFTER entered_by;
ALTER TABLE wyc_ratings MODIFY COLUMN entered_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP;
