/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestsRouteImport } from './routes/tests'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as SetCurrentQuarterRouteImport } from './routes/set-current-quarter'
import { Route as RatingsRouteImport } from './routes/ratings'
import { Route as RatingTypesRouteImport } from './routes/rating-types'
import { Route as QuartersRouteImport } from './routes/quarters'
import { Route as PrivilegesRouteImport } from './routes/privileges'
import { Route as PositionsRouteImport } from './routes/positions'
import { Route as OfficersRouteImport } from './routes/officers'
import { Route as MyLessonsRouteImport } from './routes/my-lessons'
import { Route as MembershipProcessingRouteImport } from './routes/membership-processing'
import { Route as MembersRouteImport } from './routes/members'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LessonsRouteImport } from './routes/lessons'
import { Route as LessonListRouteImport } from './routes/lesson-list'
import { Route as HonoraryRouteImport } from './routes/honorary'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ForbiddenRouteImport } from './routes/forbidden'
import { Route as ClassTypesRouteImport } from './routes/class-types'
import { Route as ChiefsRouteImport } from './routes/chiefs'
import { Route as CheckoutsRouteImport } from './routes/checkouts'
import { Route as BoatTypesRouteImport } from './routes/boat-types'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignupLessonIndexRouteImport } from './routes/signup.$lessonIndex'
import { Route as RatingsRatingIndexRouteImport } from './routes/ratings_.$ratingIndex'
import { Route as MembersWycNumberRouteImport } from './routes/members_.$wycNumber'
import { Route as LessonsLessonIndexRouteImport } from './routes/lessons_.$lessonIndex'

const TestsRoute = TestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => rootRouteImport,
} as any)
const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SetCurrentQuarterRoute = SetCurrentQuarterRouteImport.update({
  id: '/set-current-quarter',
  path: '/set-current-quarter',
  getParentRoute: () => rootRouteImport,
} as any)
const RatingsRoute = RatingsRouteImport.update({
  id: '/ratings',
  path: '/ratings',
  getParentRoute: () => rootRouteImport,
} as any)
const RatingTypesRoute = RatingTypesRouteImport.update({
  id: '/rating-types',
  path: '/rating-types',
  getParentRoute: () => rootRouteImport,
} as any)
const QuartersRoute = QuartersRouteImport.update({
  id: '/quarters',
  path: '/quarters',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivilegesRoute = PrivilegesRouteImport.update({
  id: '/privileges',
  path: '/privileges',
  getParentRoute: () => rootRouteImport,
} as any)
const PositionsRoute = PositionsRouteImport.update({
  id: '/positions',
  path: '/positions',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficersRoute = OfficersRouteImport.update({
  id: '/officers',
  path: '/officers',
  getParentRoute: () => rootRouteImport,
} as any)
const MyLessonsRoute = MyLessonsRouteImport.update({
  id: '/my-lessons',
  path: '/my-lessons',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipProcessingRoute = MembershipProcessingRouteImport.update({
  id: '/membership-processing',
  path: '/membership-processing',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsRoute = LessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonListRoute = LessonListRouteImport.update({
  id: '/lesson-list',
  path: '/lesson-list',
  getParentRoute: () => rootRouteImport,
} as any)
const HonoraryRoute = HonoraryRouteImport.update({
  id: '/honorary',
  path: '/honorary',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassTypesRoute = ClassTypesRouteImport.update({
  id: '/class-types',
  path: '/class-types',
  getParentRoute: () => rootRouteImport,
} as any)
const ChiefsRoute = ChiefsRouteImport.update({
  id: '/chiefs',
  path: '/chiefs',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutsRoute = CheckoutsRouteImport.update({
  id: '/checkouts',
  path: '/checkouts',
  getParentRoute: () => rootRouteImport,
} as any)
const BoatTypesRoute = BoatTypesRouteImport.update({
  id: '/boat-types',
  path: '/boat-types',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupLessonIndexRoute = SignupLessonIndexRouteImport.update({
  id: '/signup/$lessonIndex',
  path: '/signup/$lessonIndex',
  getParentRoute: () => rootRouteImport,
} as any)
const RatingsRatingIndexRoute = RatingsRatingIndexRouteImport.update({
  id: '/ratings_/$ratingIndex',
  path: '/ratings/$ratingIndex',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersWycNumberRoute = MembersWycNumberRouteImport.update({
  id: '/members_/$wycNumber',
  path: '/members/$wycNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsLessonIndexRoute = LessonsLessonIndexRouteImport.update({
  id: '/lessons_/$lessonIndex',
  path: '/lessons/$lessonIndex',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/boat-types': typeof BoatTypesRoute
  '/checkouts': typeof CheckoutsRoute
  '/chiefs': typeof ChiefsRoute
  '/class-types': typeof ClassTypesRoute
  '/forbidden': typeof ForbiddenRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/honorary': typeof HonoraryRoute
  '/lesson-list': typeof LessonListRoute
  '/lessons': typeof LessonsRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRoute
  '/membership-processing': typeof MembershipProcessingRoute
  '/my-lessons': typeof MyLessonsRoute
  '/officers': typeof OfficersRoute
  '/positions': typeof PositionsRoute
  '/privileges': typeof PrivilegesRoute
  '/quarters': typeof QuartersRoute
  '/rating-types': typeof RatingTypesRoute
  '/ratings': typeof RatingsRoute
  '/set-current-quarter': typeof SetCurrentQuarterRoute
  '/set-password': typeof SetPasswordRoute
  '/tests': typeof TestsRoute
  '/lessons/$lessonIndex': typeof LessonsLessonIndexRoute
  '/members/$wycNumber': typeof MembersWycNumberRoute
  '/ratings/$ratingIndex': typeof RatingsRatingIndexRoute
  '/signup/$lessonIndex': typeof SignupLessonIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/boat-types': typeof BoatTypesRoute
  '/checkouts': typeof CheckoutsRoute
  '/chiefs': typeof ChiefsRoute
  '/class-types': typeof ClassTypesRoute
  '/forbidden': typeof ForbiddenRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/honorary': typeof HonoraryRoute
  '/lesson-list': typeof LessonListRoute
  '/lessons': typeof LessonsRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRoute
  '/membership-processing': typeof MembershipProcessingRoute
  '/my-lessons': typeof MyLessonsRoute
  '/officers': typeof OfficersRoute
  '/positions': typeof PositionsRoute
  '/privileges': typeof PrivilegesRoute
  '/quarters': typeof QuartersRoute
  '/rating-types': typeof RatingTypesRoute
  '/ratings': typeof RatingsRoute
  '/set-current-quarter': typeof SetCurrentQuarterRoute
  '/set-password': typeof SetPasswordRoute
  '/tests': typeof TestsRoute
  '/lessons/$lessonIndex': typeof LessonsLessonIndexRoute
  '/members/$wycNumber': typeof MembersWycNumberRoute
  '/ratings/$ratingIndex': typeof RatingsRatingIndexRoute
  '/signup/$lessonIndex': typeof SignupLessonIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/boat-types': typeof BoatTypesRoute
  '/checkouts': typeof CheckoutsRoute
  '/chiefs': typeof ChiefsRoute
  '/class-types': typeof ClassTypesRoute
  '/forbidden': typeof ForbiddenRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/honorary': typeof HonoraryRoute
  '/lesson-list': typeof LessonListRoute
  '/lessons': typeof LessonsRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRoute
  '/membership-processing': typeof MembershipProcessingRoute
  '/my-lessons': typeof MyLessonsRoute
  '/officers': typeof OfficersRoute
  '/positions': typeof PositionsRoute
  '/privileges': typeof PrivilegesRoute
  '/quarters': typeof QuartersRoute
  '/rating-types': typeof RatingTypesRoute
  '/ratings': typeof RatingsRoute
  '/set-current-quarter': typeof SetCurrentQuarterRoute
  '/set-password': typeof SetPasswordRoute
  '/tests': typeof TestsRoute
  '/lessons_/$lessonIndex': typeof LessonsLessonIndexRoute
  '/members_/$wycNumber': typeof MembersWycNumberRoute
  '/ratings_/$ratingIndex': typeof RatingsRatingIndexRoute
  '/signup/$lessonIndex': typeof SignupLessonIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/boat-types'
    | '/checkouts'
    | '/chiefs'
    | '/class-types'
    | '/forbidden'
    | '/forgot-password'
    | '/honorary'
    | '/lesson-list'
    | '/lessons'
    | '/login'
    | '/members'
    | '/membership-processing'
    | '/my-lessons'
    | '/officers'
    | '/positions'
    | '/privileges'
    | '/quarters'
    | '/rating-types'
    | '/ratings'
    | '/set-current-quarter'
    | '/set-password'
    | '/tests'
    | '/lessons/$lessonIndex'
    | '/members/$wycNumber'
    | '/ratings/$ratingIndex'
    | '/signup/$lessonIndex'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/boat-types'
    | '/checkouts'
    | '/chiefs'
    | '/class-types'
    | '/forbidden'
    | '/forgot-password'
    | '/honorary'
    | '/lesson-list'
    | '/lessons'
    | '/login'
    | '/members'
    | '/membership-processing'
    | '/my-lessons'
    | '/officers'
    | '/positions'
    | '/privileges'
    | '/quarters'
    | '/rating-types'
    | '/ratings'
    | '/set-current-quarter'
    | '/set-password'
    | '/tests'
    | '/lessons/$lessonIndex'
    | '/members/$wycNumber'
    | '/ratings/$ratingIndex'
    | '/signup/$lessonIndex'
  id:
    | '__root__'
    | '/'
    | '/boat-types'
    | '/checkouts'
    | '/chiefs'
    | '/class-types'
    | '/forbidden'
    | '/forgot-password'
    | '/honorary'
    | '/lesson-list'
    | '/lessons'
    | '/login'
    | '/members'
    | '/membership-processing'
    | '/my-lessons'
    | '/officers'
    | '/positions'
    | '/privileges'
    | '/quarters'
    | '/rating-types'
    | '/ratings'
    | '/set-current-quarter'
    | '/set-password'
    | '/tests'
    | '/lessons_/$lessonIndex'
    | '/members_/$wycNumber'
    | '/ratings_/$ratingIndex'
    | '/signup/$lessonIndex'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoatTypesRoute: typeof BoatTypesRoute
  CheckoutsRoute: typeof CheckoutsRoute
  ChiefsRoute: typeof ChiefsRoute
  ClassTypesRoute: typeof ClassTypesRoute
  ForbiddenRoute: typeof ForbiddenRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HonoraryRoute: typeof HonoraryRoute
  LessonListRoute: typeof LessonListRoute
  LessonsRoute: typeof LessonsRoute
  LoginRoute: typeof LoginRoute
  MembersRoute: typeof MembersRoute
  MembershipProcessingRoute: typeof MembershipProcessingRoute
  MyLessonsRoute: typeof MyLessonsRoute
  OfficersRoute: typeof OfficersRoute
  PositionsRoute: typeof PositionsRoute
  PrivilegesRoute: typeof PrivilegesRoute
  QuartersRoute: typeof QuartersRoute
  RatingTypesRoute: typeof RatingTypesRoute
  RatingsRoute: typeof RatingsRoute
  SetCurrentQuarterRoute: typeof SetCurrentQuarterRoute
  SetPasswordRoute: typeof SetPasswordRoute
  TestsRoute: typeof TestsRoute
  LessonsLessonIndexRoute: typeof LessonsLessonIndexRoute
  MembersWycNumberRoute: typeof MembersWycNumberRoute
  RatingsRatingIndexRoute: typeof RatingsRatingIndexRoute
  SignupLessonIndexRoute: typeof SignupLessonIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tests': {
      id: '/tests'
      path: '/tests'
      fullPath: '/tests'
      preLoaderRoute: typeof TestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/set-password': {
      id: '/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/set-current-quarter': {
      id: '/set-current-quarter'
      path: '/set-current-quarter'
      fullPath: '/set-current-quarter'
      preLoaderRoute: typeof SetCurrentQuarterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ratings': {
      id: '/ratings'
      path: '/ratings'
      fullPath: '/ratings'
      preLoaderRoute: typeof RatingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rating-types': {
      id: '/rating-types'
      path: '/rating-types'
      fullPath: '/rating-types'
      preLoaderRoute: typeof RatingTypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quarters': {
      id: '/quarters'
      path: '/quarters'
      fullPath: '/quarters'
      preLoaderRoute: typeof QuartersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privileges': {
      id: '/privileges'
      path: '/privileges'
      fullPath: '/privileges'
      preLoaderRoute: typeof PrivilegesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/positions': {
      id: '/positions'
      path: '/positions'
      fullPath: '/positions'
      preLoaderRoute: typeof PositionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officers': {
      id: '/officers'
      path: '/officers'
      fullPath: '/officers'
      preLoaderRoute: typeof OfficersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-lessons': {
      id: '/my-lessons'
      path: '/my-lessons'
      fullPath: '/my-lessons'
      preLoaderRoute: typeof MyLessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership-processing': {
      id: '/membership-processing'
      path: '/membership-processing'
      fullPath: '/membership-processing'
      preLoaderRoute: typeof MembershipProcessingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons': {
      id: '/lessons'
      path: '/lessons'
      fullPath: '/lessons'
      preLoaderRoute: typeof LessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson-list': {
      id: '/lesson-list'
      path: '/lesson-list'
      fullPath: '/lesson-list'
      preLoaderRoute: typeof LessonListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/honorary': {
      id: '/honorary'
      path: '/honorary'
      fullPath: '/honorary'
      preLoaderRoute: typeof HonoraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/class-types': {
      id: '/class-types'
      path: '/class-types'
      fullPath: '/class-types'
      preLoaderRoute: typeof ClassTypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chiefs': {
      id: '/chiefs'
      path: '/chiefs'
      fullPath: '/chiefs'
      preLoaderRoute: typeof ChiefsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkouts': {
      id: '/checkouts'
      path: '/checkouts'
      fullPath: '/checkouts'
      preLoaderRoute: typeof CheckoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boat-types': {
      id: '/boat-types'
      path: '/boat-types'
      fullPath: '/boat-types'
      preLoaderRoute: typeof BoatTypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/$lessonIndex': {
      id: '/signup/$lessonIndex'
      path: '/signup/$lessonIndex'
      fullPath: '/signup/$lessonIndex'
      preLoaderRoute: typeof SignupLessonIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ratings_/$ratingIndex': {
      id: '/ratings_/$ratingIndex'
      path: '/ratings/$ratingIndex'
      fullPath: '/ratings/$ratingIndex'
      preLoaderRoute: typeof RatingsRatingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members_/$wycNumber': {
      id: '/members_/$wycNumber'
      path: '/members/$wycNumber'
      fullPath: '/members/$wycNumber'
      preLoaderRoute: typeof MembersWycNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons_/$lessonIndex': {
      id: '/lessons_/$lessonIndex'
      path: '/lessons/$lessonIndex'
      fullPath: '/lessons/$lessonIndex'
      preLoaderRoute: typeof LessonsLessonIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoatTypesRoute: BoatTypesRoute,
  CheckoutsRoute: CheckoutsRoute,
  ChiefsRoute: ChiefsRoute,
  ClassTypesRoute: ClassTypesRoute,
  ForbiddenRoute: ForbiddenRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HonoraryRoute: HonoraryRoute,
  LessonListRoute: LessonListRoute,
  LessonsRoute: LessonsRoute,
  LoginRoute: LoginRoute,
  MembersRoute: MembersRoute,
  MembershipProcessingRoute: MembershipProcessingRoute,
  MyLessonsRoute: MyLessonsRoute,
  OfficersRoute: OfficersRoute,
  PositionsRoute: PositionsRoute,
  PrivilegesRoute: PrivilegesRoute,
  QuartersRoute: QuartersRoute,
  RatingTypesRoute: RatingTypesRoute,
  RatingsRoute: RatingsRoute,
  SetCurrentQuarterRoute: SetCurrentQuarterRoute,
  SetPasswordRoute: SetPasswordRoute,
  TestsRoute: TestsRoute,
  LessonsLessonIndexRoute: LessonsLessonIndexRoute,
  MembersWycNumberRoute: MembersWycNumberRoute,
  RatingsRatingIndexRoute: RatingsRatingIndexRoute,
  SignupLessonIndexRoute: SignupLessonIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
