/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as RatingsRouteImport } from './routes/ratings'
import { Route as PrivilegesRouteImport } from './routes/privileges'
import { Route as OfficersRouteImport } from './routes/officers'
import { Route as MyLessonsRouteImport } from './routes/my-lessons'
import { Route as MembershipProcessingRouteImport } from './routes/membership-processing'
import { Route as MembersRouteImport } from './routes/members'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LessonsRouteImport } from './routes/lessons'
import { Route as HonoraryRouteImport } from './routes/honorary'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ForbiddenRouteImport } from './routes/forbidden'
import { Route as EmailTestRouteImport } from './routes/email-test'
import { Route as ChiefsRouteImport } from './routes/chiefs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RatingsRatingIndexRouteImport } from './routes/ratings_.$ratingIndex'
import { Route as MembersWycNumberRouteImport } from './routes/members_.$wycNumber'
import { Route as LessonsLessonIndexRouteImport } from './routes/lessons_.$lessonIndex'

const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RatingsRoute = RatingsRouteImport.update({
  id: '/ratings',
  path: '/ratings',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivilegesRoute = PrivilegesRouteImport.update({
  id: '/privileges',
  path: '/privileges',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficersRoute = OfficersRouteImport.update({
  id: '/officers',
  path: '/officers',
  getParentRoute: () => rootRouteImport,
} as any)
const MyLessonsRoute = MyLessonsRouteImport.update({
  id: '/my-lessons',
  path: '/my-lessons',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipProcessingRoute = MembershipProcessingRouteImport.update({
  id: '/membership-processing',
  path: '/membership-processing',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsRoute = LessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => rootRouteImport,
} as any)
const HonoraryRoute = HonoraryRouteImport.update({
  id: '/honorary',
  path: '/honorary',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailTestRoute = EmailTestRouteImport.update({
  id: '/email-test',
  path: '/email-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ChiefsRoute = ChiefsRouteImport.update({
  id: '/chiefs',
  path: '/chiefs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RatingsRatingIndexRoute = RatingsRatingIndexRouteImport.update({
  id: '/ratings_/$ratingIndex',
  path: '/ratings/$ratingIndex',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersWycNumberRoute = MembersWycNumberRouteImport.update({
  id: '/members_/$wycNumber',
  path: '/members/$wycNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsLessonIndexRoute = LessonsLessonIndexRouteImport.update({
  id: '/lessons_/$lessonIndex',
  path: '/lessons/$lessonIndex',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chiefs': typeof ChiefsRoute
  '/email-test': typeof EmailTestRoute
  '/forbidden': typeof ForbiddenRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/honorary': typeof HonoraryRoute
  '/lessons': typeof LessonsRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRoute
  '/membership-processing': typeof MembershipProcessingRoute
  '/my-lessons': typeof MyLessonsRoute
  '/officers': typeof OfficersRoute
  '/privileges': typeof PrivilegesRoute
  '/ratings': typeof RatingsRoute
  '/set-password': typeof SetPasswordRoute
  '/lessons/$lessonIndex': typeof LessonsLessonIndexRoute
  '/members/$wycNumber': typeof MembersWycNumberRoute
  '/ratings/$ratingIndex': typeof RatingsRatingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chiefs': typeof ChiefsRoute
  '/email-test': typeof EmailTestRoute
  '/forbidden': typeof ForbiddenRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/honorary': typeof HonoraryRoute
  '/lessons': typeof LessonsRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRoute
  '/membership-processing': typeof MembershipProcessingRoute
  '/my-lessons': typeof MyLessonsRoute
  '/officers': typeof OfficersRoute
  '/privileges': typeof PrivilegesRoute
  '/ratings': typeof RatingsRoute
  '/set-password': typeof SetPasswordRoute
  '/lessons/$lessonIndex': typeof LessonsLessonIndexRoute
  '/members/$wycNumber': typeof MembersWycNumberRoute
  '/ratings/$ratingIndex': typeof RatingsRatingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chiefs': typeof ChiefsRoute
  '/email-test': typeof EmailTestRoute
  '/forbidden': typeof ForbiddenRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/honorary': typeof HonoraryRoute
  '/lessons': typeof LessonsRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRoute
  '/membership-processing': typeof MembershipProcessingRoute
  '/my-lessons': typeof MyLessonsRoute
  '/officers': typeof OfficersRoute
  '/privileges': typeof PrivilegesRoute
  '/ratings': typeof RatingsRoute
  '/set-password': typeof SetPasswordRoute
  '/lessons_/$lessonIndex': typeof LessonsLessonIndexRoute
  '/members_/$wycNumber': typeof MembersWycNumberRoute
  '/ratings_/$ratingIndex': typeof RatingsRatingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chiefs'
    | '/email-test'
    | '/forbidden'
    | '/forgot-password'
    | '/honorary'
    | '/lessons'
    | '/login'
    | '/members'
    | '/membership-processing'
    | '/my-lessons'
    | '/officers'
    | '/privileges'
    | '/ratings'
    | '/set-password'
    | '/lessons/$lessonIndex'
    | '/members/$wycNumber'
    | '/ratings/$ratingIndex'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chiefs'
    | '/email-test'
    | '/forbidden'
    | '/forgot-password'
    | '/honorary'
    | '/lessons'
    | '/login'
    | '/members'
    | '/membership-processing'
    | '/my-lessons'
    | '/officers'
    | '/privileges'
    | '/ratings'
    | '/set-password'
    | '/lessons/$lessonIndex'
    | '/members/$wycNumber'
    | '/ratings/$ratingIndex'
  id:
    | '__root__'
    | '/'
    | '/chiefs'
    | '/email-test'
    | '/forbidden'
    | '/forgot-password'
    | '/honorary'
    | '/lessons'
    | '/login'
    | '/members'
    | '/membership-processing'
    | '/my-lessons'
    | '/officers'
    | '/privileges'
    | '/ratings'
    | '/set-password'
    | '/lessons_/$lessonIndex'
    | '/members_/$wycNumber'
    | '/ratings_/$ratingIndex'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChiefsRoute: typeof ChiefsRoute
  EmailTestRoute: typeof EmailTestRoute
  ForbiddenRoute: typeof ForbiddenRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HonoraryRoute: typeof HonoraryRoute
  LessonsRoute: typeof LessonsRoute
  LoginRoute: typeof LoginRoute
  MembersRoute: typeof MembersRoute
  MembershipProcessingRoute: typeof MembershipProcessingRoute
  MyLessonsRoute: typeof MyLessonsRoute
  OfficersRoute: typeof OfficersRoute
  PrivilegesRoute: typeof PrivilegesRoute
  RatingsRoute: typeof RatingsRoute
  SetPasswordRoute: typeof SetPasswordRoute
  LessonsLessonIndexRoute: typeof LessonsLessonIndexRoute
  MembersWycNumberRoute: typeof MembersWycNumberRoute
  RatingsRatingIndexRoute: typeof RatingsRatingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/set-password': {
      id: '/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ratings': {
      id: '/ratings'
      path: '/ratings'
      fullPath: '/ratings'
      preLoaderRoute: typeof RatingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privileges': {
      id: '/privileges'
      path: '/privileges'
      fullPath: '/privileges'
      preLoaderRoute: typeof PrivilegesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officers': {
      id: '/officers'
      path: '/officers'
      fullPath: '/officers'
      preLoaderRoute: typeof OfficersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-lessons': {
      id: '/my-lessons'
      path: '/my-lessons'
      fullPath: '/my-lessons'
      preLoaderRoute: typeof MyLessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership-processing': {
      id: '/membership-processing'
      path: '/membership-processing'
      fullPath: '/membership-processing'
      preLoaderRoute: typeof MembershipProcessingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons': {
      id: '/lessons'
      path: '/lessons'
      fullPath: '/lessons'
      preLoaderRoute: typeof LessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/honorary': {
      id: '/honorary'
      path: '/honorary'
      fullPath: '/honorary'
      preLoaderRoute: typeof HonoraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-test': {
      id: '/email-test'
      path: '/email-test'
      fullPath: '/email-test'
      preLoaderRoute: typeof EmailTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chiefs': {
      id: '/chiefs'
      path: '/chiefs'
      fullPath: '/chiefs'
      preLoaderRoute: typeof ChiefsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ratings_/$ratingIndex': {
      id: '/ratings_/$ratingIndex'
      path: '/ratings/$ratingIndex'
      fullPath: '/ratings/$ratingIndex'
      preLoaderRoute: typeof RatingsRatingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members_/$wycNumber': {
      id: '/members_/$wycNumber'
      path: '/members/$wycNumber'
      fullPath: '/members/$wycNumber'
      preLoaderRoute: typeof MembersWycNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons_/$lessonIndex': {
      id: '/lessons_/$lessonIndex'
      path: '/lessons/$lessonIndex'
      fullPath: '/lessons/$lessonIndex'
      preLoaderRoute: typeof LessonsLessonIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChiefsRoute: ChiefsRoute,
  EmailTestRoute: EmailTestRoute,
  ForbiddenRoute: ForbiddenRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HonoraryRoute: HonoraryRoute,
  LessonsRoute: LessonsRoute,
  LoginRoute: LoginRoute,
  MembersRoute: MembersRoute,
  MembershipProcessingRoute: MembershipProcessingRoute,
  MyLessonsRoute: MyLessonsRoute,
  OfficersRoute: OfficersRoute,
  PrivilegesRoute: PrivilegesRoute,
  RatingsRoute: RatingsRoute,
  SetPasswordRoute: SetPasswordRoute,
  LessonsLessonIndexRoute: LessonsLessonIndexRoute,
  MembersWycNumberRoute: MembersWycNumberRoute,
  RatingsRatingIndexRoute: RatingsRatingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
